version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    - "5005:5005"
    - "9010:9010"
    environment:
    - APP_NAME=pokemonspeare-api